api_platform:
    title: Source Web Console
    version: 1.0.0
    formats:
        jsonld: ["application/ld+json"]
    docs_formats:
        html: ["text/html"]
        jsonld: ["application/ld+json"]
        jsonopenapi: ["application/vnd.openapi+json"]
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    use_symfony_listeners: true