when@prod:
    framework:
        cache:
            app: cache_pool
            pools:
                cache_pool:
                    adapters:
                      - {name: cache.adapter.redis, provider: "Redis"}
                      - {name: cache.adapter.doctrine_dbal}
                      - {name: cache.adapter.filesystem}
            system: cache.adapter.system