framework:
    secret: "%env(APP_SECRET)%"
    csrf_protection: true
    http_method_override: false # par défaut à partir de Symfony 7
    handle_all_throwables: true # par défaut à partir de Symfony 7
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_cache: true