framework:
    secret: "%env(APP_SECRET)%"
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_samesite: lax
    csrf_protection: true
    http_method_override: false # par défaut à partir de Symfony 7
    handle_all_throwables: true # par défaut à partir de Symfony 7

when@test:
    framework:
        test: true
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_cache: true