framework:
    secret: "%env(APP_SECRET)%"
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_samesite: lax
    csrf_protection: true

when@test:
    framework:
        test: true
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_cache: true