knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: "%env(GOOGLE_CLIENT_ID)%"
            client_secret: "%env(GOOGLE_CLIENT_SECRET)%"
            redirect_route: user_oauth_check
            redirect_params: {name: "google"}
        github:
            type: github
            client_id: "%env(GITHUB_CLIENT_ID)%"
            client_secret: "%env(GITHUB_CLIENT_SECRET)%"
            redirect_route: user_oauth_check
            redirect_params: {name: "github"}