monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                channels: ["!event", "!doctrine", "!console"]
                process_psr_3_messages: false

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                handler: nested
                channels: ["!event"]
                action_level: error
                excluded_http_codes: [404, 405]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                handler: nested
                buffer_size: 50
                action_level: error
                excluded_http_codes: [404, 405]
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                channels: ["!event", "!doctrine"]
                process_psr_3_messages: false
            deprecation:
                type: stream
                path: php://stderr
                channels: [deprecation]
                formatter: monolog.formatter.json