monolog:
    handlers:
        main:
            type: fingers_crossed
            handler: nested
            channels: ["!event", "!request"]
            action_level: debug
            excluded_http_codes: [404, 405]
        nested:
            type: rotating_file
            level: debug
            max_files: 14
            filename_format: "{date}"
        console:
            type: console
            channels: ["!event", "!doctrine"]
            process_psr_3_messages: false

when@prod:
    monolog:
        handlers:
            main:
                buffer_size: 50
                action_level: info
            nested:
                level: info