nelmio_cors:
    paths:
        "^/": null
    defaults:
        max_age: 3600
        origin_regex: true
        allow_origin: ["^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]