framework:
    rate_limiter:
        api:
            limit: 60
            policy: "sliding_window"
            interval: "1 minute"

when@test:
    framework:
        rate_limiter:
            api:
                limit: 1000