security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            logout:
                path: app_user_logout
                target: app_index_index
            provider: app_user_provider
            form_login:
                login_path: app_index_index
                check_path: app_user_login
                enable_csrf: true
            remember_me:
                secure: true
                secret: "%kernel.secret%"
                lifetime: 604800
                samesite: strict
                token_provider:
                    doctrine: true
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                cost: 4
                time_cost: 3
                algorithm: auto
                memory_cost: 10