security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            remember_me:
                secure: true
                secret: "%kernel.secret%"
                lifetime: 604800
                samesite: strict
            login_link:
                max_uses: 1
                lifetime: 86400
                check_route: user_onetime
                signature_properties: ["id", "username"]
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_DONOR: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_DONOR]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                cost: 4
                time_cost: 3
                algorithm: auto
                memory_cost: 10