name: source-web-console

services:
    cache:
        image: valkey/valkey:8
        command: >
            --requirepass ${CACHE_PASSWORD}
            --maxmemory 128mb
            --maxmemory-policy allkeys-lru
        volumes:
            - valkey_data:/data
        healthcheck:
            test: valkey-cli --raw incr ping
            retries: 3
            timeout: 5s
            start_period: 30s

    database:
        image: mariadb:12
        command: --collation-server=utf8mb4_unicode_ci
        volumes:
            - mariadb_data:/var/lib/mysql
        environment:
            TZ: ${APP_TIMEZONE}
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_USER: ${DATABASE_USERNAME}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
            MARIADB_AUTO_UPGRADE: true
            MARIADB_INITDB_SKIP_TZINFO: true
            MARIADB_RANDOM_ROOT_PASSWORD: true
        healthcheck:
            test: healthcheck.sh --su-mysql --connect --innodb_initialized
            retries: 3
            timeout: 5s
            start_period: 30s

    server:
        image: source-web-console
        command: docker/scripts/development/entrypoint.sh
        volumes:
            - .:/var/www/html:cached
            - /var/www/html/.git
            - /var/www/html/vendor
            - /var/www/html/var
            - /var/www/html/node_modules
        depends_on:
            cache:
                condition: service_healthy
            database:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: curl -f http://localhost:8000/
            retries: 3
            timeout: 5s
            start_period: 30s
        build:
            target: development
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - "8000:8000"
            - "8443:8443/udp"

volumes:
    valkey_data:
    mariadb_data:
