name: source-web-console

services:
    cache:
        init: true
        image: valkey/valkey:8
        restart: unless-stopped
        command: >
            --requirepass ${CACHE_PASSWORD}
            --maxmemory 128mb
            --maxmemory-policy allkeys-lru
        volumes:
            - valkey_data:/data
        env_file:
            - .env
        security_opt:
            - no-new-privileges=true
        healthcheck:
            test: valkey-cli --raw incr ping
            retries: 3
            timeout: 5s
        deploy:
            resources:
                limits:
                    pids: 16
                    cpus: "0.5"
                    memory: 128M

    database:
        init: true
        image: mariadb:12
        restart: unless-stopped
        command: --collation-server=utf8mb4_unicode_ci
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        environment:
            TZ: ${APP_TIMEZONE}
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_USER: ${DATABASE_USERNAME}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
            MARIADB_AUTO_UPGRADE: true
            MARIADB_INITDB_SKIP_TZINFO: true
            MARIADB_RANDOM_ROOT_PASSWORD: true
        security_opt:
            - no-new-privileges=true
        healthcheck:
            test: healthcheck.sh --su-mysql --connect --innodb_initialized
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 64
                    cpus: "0.5"
                    memory: 256M

    server:
        init: true
        user: "${UID:-1000}:${GID:-1000}"
        image: registry.florian-dev.fr:443/floriantrayon/source-web-console:${VERSION:-latest}
        restart: unless-stopped
        command: /var/www/html/entrypoint.sh
        volumes:
            - ./logs:/var/www/html/logs
        env_file:
            - .env
        depends_on:
            cache:
                condition: service_healthy
            database:
                condition: service_healthy
        security_opt:
            - no-new-privileges=true
        healthcheck:
            test: curl -f http://localhost:8080/
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 64
                    cpus: "1"
                    memory: 128M
        build:
            target: production
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - "8443:8443/udp"
            - "${PORT:-8080}:8080"

volumes:
    valkey_data:
    mariadb_data:
