name: source-web-console

networks:
    source_web_console:
        driver: bridge

services:
    # https://hub.docker.com/_/redis
    redis:
        image: redis:alpine
        restart: always
        command: >
            --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
        volumes:
            - ./docker/redis/config:/usr/local/etc/redis
            - ./docker/redis/database:/data
        networks:
            - source_web_console
        healthcheck:
            test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
            retries: 3
            timeout: 5s
        ports:
            - "6379:${REDIS_PORT}"

    # https://hub.docker.com/_/mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        volumes:
            - ./docker/mysql/database:/var/lib/mysql
        environment:
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_PORT: ${DATABASE_PORT}
            MARIADB_USER: ${DATABASE_USERNAME}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
            MARIADB_RANDOM_ROOT_PASSWORD: 1
        networks:
            - source_web_console
        healthcheck:
            test: healthcheck.sh --su-mysql --connect --innodb_initialized
            retries: 3
            timeout: 5s
        ports:
            - "3306:${DATABASE_PORT}"

    # https://hub.docker.com/_/phpmyadmin
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        depends_on:
            - mariadb
        environment:
            PMA_HOST: ${DATABASE_HOST}
            PMA_PORT: ${DATABASE_PORT}
            PMA_USER: ${DATABASE_USERNAME}
            PMA_PASSWORD: ${DATABASE_PASSWORD}
        networks:
            - source_web_console
        healthcheck:
            test: curl -f http://localhost
            retries: 3
            timeout: 5s
        ports:
            - "8080:80"

    # https://github.com/FlorianLeChat/Source-Web-Console
    php:
        image: source-web-console
        restart: always
        develop:
            watch:
                - action: sync
                  path: .
                  target: /var/www/html
        volumes:
            - ./public/build:/var/www/html/public/build
            - ./docker/mysql/database:/var/lib/mysql
        depends_on:
            - redis
            - mariadb
        environment:
            - WAIT_HOSTS=redis:${REDIS_PORT}, mariadb:${DATABASE_PORT}
        networks:
            - source_web_console
        healthcheck:
            test: curl -f http://127.0.0.1:9000/ 2>&1 | grep "Connection reset by peer" || curl -f http://localhost
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/Dockerfile.${APP_ENV}
        ports:
            - "8000:8000"
            - "8443:8443/udp"