# syntax=docker/dockerfile:1

# Use an customized image of PHP
# https://hub.docker.com/_/php
FROM php:alpine

# Install dependencies
RUN apk update && apk add --no-cache bash

# Install some PHP extensions
RUN curl -sSLf -o /usr/local/bin/install-php-extensions \
		https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
	chmod +x /usr/local/bin/install-php-extensions && \
	install-php-extensions zip pdo_mysql pdo_pgsql redis opcache intl

# Set the working directory to the website files
WORKDIR /var/www/html

# Install Composer for dependency management
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Add some cronjobs for Symfony custom commands
# https://github.com/webdevops/Dockerfile/issues/280#issuecomment-1311681838
RUN echo "* * * * * /usr/local/bin/php /var/www/html/bin/console app:tasks-executor > /dev/null 2>&1" >> /var/spool/cron/crontabs/root
RUN echo "0 * * * * /usr/local/bin/php /var/www/html/bin/console app:statistics-collector > /dev/null 2>&1" >> /var/spool/cron/crontabs/root

# Add wait script to wait for other services to be ready
ADD https://github.com/ufoscout/docker-compose-wait/releases/latest/download/wait /wait
RUN chmod +x /wait

# Install Symfony CLI
RUN curl -1sLf https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh | bash && \
	apk add symfony-cli

# Copy all files to the working directory
COPY --chown=www-data:www-data . .

# Use the default or custom PHP configuration (if exists)
RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini && \
	if [ -f "docker/php.ini" ]; then \
		mv "docker/php.ini" "$PHP_INI_DIR/php.ini"; \
	fi

# Change current user to www-data
USER www-data

# Install all dependencies
# Use cache mount to speed up installation of existing dependencies
RUN --mount=type=cache,target=.composer composer install

# Use the PHP custom entrypoint
# https://symfony.com/doc/current/deployment.html / https://symfony.com/doc/current/setup/file_permissions.html
RUN mkdir -p docker && echo '/wait && mkdir -p var/cache var/log && \
	/usr/local/bin/php bin/console doctrine:database:create --no-interaction --if-not-exists && \
	/usr/local/bin/php bin/console doctrine:schema:update --complete --force && \
	/usr/local/bin/php bin/console app:udp-server 127.0.0.1:8443 & \
	symfony server:start' > docker/entrypoint.sh && chmod +x docker/entrypoint.sh

CMD ["docker/entrypoint.sh"]