name: Symfony

on: workflow_call

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.2, 8.3 ]
      fail-fast: false
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: |
        npm install
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Build static assets
      run: npm run build
    - name: Create database and load fixtures
      run: |
        touch var/data.db
        php bin/console --env=test doctrine:schema:create --no-interaction
        php bin/console --env=test doctrine:fixtures:load --no-interaction
    - name: Run PHP Code Sniffer
      run: vendor/bin/phpcs -s
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --error-format=github
    - name: Run PHP Mess Detector
      run: vendor/bin/phpmd ./src github phpmd.xml.dist
    - name: Execute tests with PHPUnit
      run: vendor/bin/phpunit
